language: rust

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/download/v0.8.6/grcov-v0.8.6-x86_64-unknown-linux-gnu.tar.gz | tar jxf -

matrix:
  include:
    - os: linux
      rust: nightly

script:
  - export CARGO_INCREMENTAL=0
  - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
  - export RUSTDOCFLAGS="-Cpanic=abort"
  - cargo build --verbose $CARGO_OPTIONS
  - cargo test --verbose $CARGO_OPTIONS
  - |
    zip -0 ccov.zip `find . \( -name "rphtml*.gc*" \) -print`;
    ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
    bash <(curl -s https://codecov.io/bash) -f lcov.info;
